### ISSUE TITLE
not providing a user doesn't default to ctx.author when a day amount is provided

### ISSUE THREAD

**Issue by iHeroGH** [Voxel-Fox-Ltd/Cerberus#12]

**Comment by 4Kaylum** [comment]
What command is this in relation to?

**Comment by iHeroGH** [comment]
> What command is this in relation to?

I've only tested it with `graph`

**Comment by 4Kaylum** [comment]
Issue resolved, bot is working as intended. The user `100` was the culprit and they will not be forgiven.
