### ISSUE TITLE
Graph not showing under 24 hours old

### ISSUE THREAD

**Issue by H077y** [Voxel-Fox-Ltd/Cerberus#4]
The graph doesn't show if the bot had been in the server for a day old

**Comment by 4Kaylum** [comment]
If a user (or the bot) hasn't been in the server for 48 hours then nothing will be shown for their graph. I think the solution I want for this is to just increase the resolution for time periods of 2 days or less. 

This would be to be done by changing the interval in the SQL for the graph command. I think.

**Comment by 4Kaylum** [comment]
Closed with a78858a8b4deb0a47867469eae4124994870e468 and 7cd8bda0336cf8ea0a7bd5c58ca859913838fe3e.
